version: '3.9'
services:
  movie-database:
    build:
      context: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - movie-db-vol:/var/lib/postgresql/data
volumes:
  movie-db-vol:


